const CHARACTERS = {
  cat2: {
    name: '猫猫',
    sprite: 'cat2.png',
    frameWidth: 32,
    frameHeight: 32,
    cols: 4,
    scale: 3,
    walkSpeed: 0.08,
    states: {
      walk: {
        directionRows: { down: 0, right: 1, up: 2, left: 3 },
        frameInterval: 350,
      },
      idle: {
        row: 4,
        frameInterval: 450,
        loops: false,
      },
      lick: {
        row: 5,
        frameInterval: 400,
        loops: true,
      },
      lie_down: {
        row: 6,
        frameInterval: 400,
        loops: false,
      },
      sleep: {
        row: 7,
        frameInterval: 600,
        loops: false,
      },
    },
    transitions: {
      walk: [
        { state: 'idle', weight: 0.25 },
        { state: 'walk', weight: 0.25 },
        { state: 'lie_down', weight: 0.15 },
        { state: 'lick', weight: 0.15 },
        { state: 'sleep', weight: 0.20 },
      ],
      idle: { waitMin: 3000, waitMax: 6000, next: 'walk' },
      lick: { repeatMin: 2, repeatMax: 4, next: 'walk' },
      lie_down: { waitMin: 3000, waitMax: 6000, next: 'walk' },
      sleep: { waitMin: 5000, waitMax: 10000, next: 'walk' },
    },
    walkDurationMin: 2000,
    walkDurationMax: 5000,
    doubleClickActions: [
      { state: 'lick', weight: 0.4 },
      { state: 'lie_down', weight: 0.3 },
      { state: 'sleep', weight: 0.3 },
    ],
  },
  sebastian: {
    name: 'Sebastian',
    sprite: 'characters/Sebastian.png',
    frameWidth: 16,
    frameHeight: 32,
    cols: 4,
    scale: 3,
    walkSpeed: 0.12,
    states: {
      walk: {
        directionRows: { down: 0, right: 1, up: 2, left: 3 },
        frameInterval: 200,
      },
      idle: {
        row: 0,
        frameInterval: 600,
        loops: false,
      },
      read: {
        row: 4,
        frameInterval: 400,
        loops: false,
      },
      sit: {
        row: 5,
        frameInterval: 400,
        loops: false,
      },
      coffee: {
        row: 6,
        frameInterval: 400,
        loops: false,
      },
      typing: {
        row: 7,
        frameInterval: 300,
        loops: true,
      },
      smoking: {
        row: 8,
        frameInterval: 500,
        loops: true,
      },
      look_down: {
        row: 9,
        frameInterval: 400,
        loops: false,
      },
      look_right: {
        row: 10,
        frameInterval: 400,
        loops: false,
      },
      look_up: {
        row: 11,
        frameInterval: 400,
        loops: false,
      },
      look_left: {
        row: 12,
        frameInterval: 400,
        loops: false,
      },
      motorcycle: {
        row: 13,
        frameInterval: 300,
        loops: true,
      },
      game: {
        row: 14,
        frameInterval: 300,
        loops: true,
      },
    },
    transitions: {
      walk: [
        { state: 'idle', weight: 0.25 },
        { state: 'walk', weight: 0.25 },
        { state: 'sit', weight: 0.10 },
        { state: 'typing', weight: 0.10 },
        { state: 'smoking', weight: 0.10 },
        { state: 'look_down', weight: 0.05 },
        { state: 'look_right', weight: 0.05 },
        { state: 'look_up', weight: 0.05 },
        { state: 'look_left', weight: 0.05 },
      ],
      idle: { waitMin: 3000, waitMax: 6000, next: 'walk' },
      read: { waitMin: 4000, waitMax: 8000, next: 'walk' },
      sit: { waitMin: 4000, waitMax: 8000, next: 'walk' },
      coffee: { waitMin: 3000, waitMax: 6000, next: 'walk' },
      typing: { repeatMin: 2, repeatMax: 5, next: 'walk' },
      smoking: { waitMin: 5000, waitMax: 10000, next: 'walk' },
      look_down: { waitMin: 3000, waitMax: 5000, next: 'walk' },
      look_right: { waitMin: 3000, waitMax: 5000, next: 'walk' },
      look_up: { waitMin: 3000, waitMax: 5000, next: 'walk' },
      look_left: { waitMin: 3000, waitMax: 5000, next: 'walk' },
      motorcycle: { repeatMin: 3, repeatMax: 6, next: 'walk' },
      game: { repeatMin: 3, repeatMax: 6, next: 'walk' },
    },
    walkDurationMin: 2000,
    walkDurationMax: 4000,
    doubleClickActions: [
      { state: 'sit', weight: 0.25 },
      { state: 'typing', weight: 0.20 },
      { state: 'smoking', weight: 0.20 },
      { state: 'coffee', weight: 0.15 },
      { state: 'read', weight: 0.10 },
      { state: 'game', weight: 0.10 },
    ],
  },
};

module.exports = CHARACTERS;